apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: | #These IPs are for metallb in lxc containers- HAs to abive by the CIDR inside lxc container
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.101.169.10-10.101.169.120 
