name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -o release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - uses: actions/upload-artifact@v2
      with:
        name: profile-artifact
        path: release/ # or path/to/artifact
  
  package:
    name: "Package and push"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: profile-artifact
      - name: Buld and push image
        uses: docker/build-push-action@v1.1.0
